### ISSUE TITLE
Clarification on data in `data_rmarkdown`

### ISSUE THREAD

**Issue by lianov** [youyupei/bc_whitelist_analysis#1]
Hello, I have a brief question regarding the input data for this repo, and I hope it is alright to ask here.

Given the following inputs from the `data_rmarkdown` available at <https://melbourne.figshare.com/articles/dataset/Analysis_data_for_BLAZE/20335203>, could you let me know what is the main difference between files which contain the `_rebase.csv` extension vs just `.csv`?  Specific files of interest are below:

```
gene_count_B+F_non_q20_rebase.csv
gene_count_B+F_q20_rebase.csv
trans_count_B+F_non_q20_rebase.csv
trans_count_B+F_q20_rebase.csv

#vs

gene_count_B+F_non_q20.csv
gene_count_B+F_q20.csv
trans_count_B+F_non_q20.csv
trans_count_B+F_q20.csv
```

I have noticed that this is only present for the GridION samples, and not PromithIon. I only ask since one of the scripts (UMAP) plots imports the files with `rebase`, while the marker gene analysis, imports the ones without it. The only reference I could find to "rebase" is the rebasecalled process in the paper, however, this was only performed to the scmixology dataset according to the methods. Any clarifications is appreciated. Thanks!

**Comment by youyupei** [comment]
Hi @lianov,

Sorry for the confusion. The `non_q20_rebase` corresponds to the dataset ID "GridION" in the [table 1](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-023-02907-y/tables/1) of the paper. It was sequenced on GridION with kit LSK110, so we called it a "non-q20" dataset to distinguish it from the Q20 dataset which was also from GridION. 

Hope this answers your question.

Regards.

**Comment by lianov** [comment]
Hi @youyupei : yep totally got that. However, my original question is relative to the `rebase` extension on the files. For example, specifically for `non_q20`, there are 2 files per gene and trasnscript quesntification:  `gene_count_B+F_non_q20_rebase.csv` vs `gene_count_B+F_non_q20.csv`. Same is also true to the `q20` dataset. Just wondering what makes these two different in the upstream analysis. Thanks!

**Comment by youyupei** [comment]
Hi @lianov,

Your are right, the files labeled with or without the tag were both basecalled using different versions of Guppy, but there should be no difference beyond that. The files with '_rebase' in the name should be used to present the final results in the paper.

As for the RMarkdown file, the most updated ones should import the version with the '_rebase' label for both datasets. If not, it might be because the uploaded Rmd file was not up-to-date. 

(Hi @Sefi196, please correct me if I was wrong).

**Comment by lianov** [comment]
Great, thanks for confirming that @youyupei!
